---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  "Template for deploying NSO 6.1"

Parameters:
  SubnetId1:
    Type: 'AWS::EC2::Subnet::Id'
  SubnetId2:
    Type: 'AWS::EC2::Subnet::Id' 
  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
  ImageId:
    Type: 'AWS::EC2::Image::Id'
  InstanceProfile:
    Type: String
  KeyName:
    Description: Pem file for access to created instance
    Type: 'AWS::EC2::KeyPair::KeyName'


Resources:

  MyInstance1NSO:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html
    Type: AWS::EC2::Instance
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: "PT5M"
    Properties:
      InstanceType: m5.2xlarge
      KeyName: !Ref KeyName
      ImageId: !Ref ImageId    
      IamInstanceProfile: !Ref InstanceProfile      
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref NSO1VNIC0
          DeviceIndex: "0"
      Tags:
        - Key: Name
          Value: NSO61
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash
          service docker start
          sleep 120
          docker start 6a1e9c264677
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource MyInstance1NSO --region ${AWS::Region}

  NSO1VNIC0:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Description: "NSO-VNIC0"
      GroupSet: 
      - !Ref SecurityGroupId
      SubnetId: !Ref SubnetId1
      Tags:
        - Key: Name
          Value: NSO-VNIC0


Outputs:
  NSOIP:
    Value: !GetAtt NSO1VNIC0.PrimaryPrivateIpAddress
    Description: The IP of NSO server